---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - python
    - python_install
    - python_virtualenvs

- import_tasks: packages.yml
  tags:
    - python
    - python_install
    - python_virtualenvs

#- import_tasks: virtualenvs.yml
#  tags:
#    - python
#    - python_install
#    - python_virtualenvs
